
spring:
  h2:
    console:
      enabled: true
      path: h2
  datasource:
    hikari:
      #jdbc-url: jdbc:h2:test_batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver


  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
